"use client";

import { useState } from "react";
import Link from "next/link";
import { useDemo } from "../../context/demo-context";
import { available, formatDate, formatQuantity, locationName, onHand, operationLabel, productName } from "../../lib/inventory";
import type { ActionResult, OperationType } from "../../types/inventory";
import { Drawer, EmptyState, PageHeading, StatusBadge, primaryButton, secondaryButton, tableClass, tdClass, thClass } from "../ui/primitives";
import { OperationForm } from "./operation-form";

const segments: Record<OperationType,string> = { receipt:"receipts", delivery:"deliveries", transfer:"transfers", adjustment:"adjustments" };

export function OperationDetailView({ type, id }: { type: OperationType; id: string }) {
  const { state, markReady, markPacked, complete, cancel } = useDemo();
  const [feedback, setFeedback] = useState<ActionResult | null>(null);
  const [editOpen, setEditOpen] = useState(false);
  const operation = state.operations.find((item) => item.id === id && item.type === type);
  if (!operation) return <EmptyState title="Document not found" description="This operation could not be found." action={<Link className={secondaryButton} href={`/operations/${segments[type]}`}>Back to {segments[type]}</Link>} />;
  function run(action: () => ActionResult) { setFeedback(action()); }
  const source = locationName(state,operation.sourceLocationId);
  const destination = locationName(state,operation.destinationLocationId);
  const isOpen = !["Done","Canceled"].includes(operation.status);
  const statusFlow = type === "adjustment" ? ["Draft","Done"] : ["Draft","Waiting","Ready","Done"];
  return <>
    <PageHeading eyebrow={operationLabel(type)} title={operation.reference} description={`${operation.contact} · Created ${formatDate(operation.createdAt)}`} action={<div className="flex flex-wrap items-center gap-2"><StatusBadge status={operation.status} className="min-h-10 px-3" /><Link className={secondaryButton} href={`/operations/${segments[type]}`}>Back to list</Link></div>} />
    <div className="mb-6 flex flex-wrap items-center gap-2 border-b border-border pb-5">
      {isOpen && ["Draft", "Waiting"].includes(operation.status) && <button className={secondaryButton} type="button" onClick={() => setEditOpen(true)}>Edit draft</button>}
      {isOpen && type !== "adjustment" && ["Draft","Waiting"].includes(operation.status) && <button className={primaryButton} type="button" onClick={() => run(() => markReady(id))}>Mark ready</button>}
      {isOpen && type === "delivery" && operation.status === "Ready" && !operation.packed && <button className={primaryButton} type="button" onClick={() => run(() => markPacked(id))}>Confirm picked & packed</button>}
      {isOpen && (operation.status === "Ready" || type === "adjustment" && operation.status === "Draft") && <button className={type === "delivery" && !operation.packed ? secondaryButton : primaryButton} type="button" onClick={() => run(() => complete(id))}>{type === "receipt" ? "Receive stock" : type === "delivery" ? "Complete delivery" : type === "transfer" ? "Complete transfer" : "Post count"}</button>}
      {isOpen && <button type="button" className={secondaryButton} onClick={() => run(() => cancel(id))}>Cancel document</button>}
      {operation.status === "Done" && <button className={secondaryButton} type="button" onClick={() => window.print()}>Print document</button>}
    </div>
    {editOpen && <Drawer title={`Edit ${operation.reference}`} onClose={() => setEditOpen(false)}><OperationForm type={type} operation={operation} onClose={() => setEditOpen(false)} /></Drawer>}
    {feedback && <p role="status" className={`mb-6 rounded-md px-4 py-3 text-sm ${feedback.ok ? "bg-ok-wash text-ok-ink" : "bg-bad-wash text-bad-ink"}`}>{feedback.message}</p>}
    {operation.status === "Waiting" && <p className="mb-6 rounded-md bg-warn-wash px-4 py-3 text-sm text-warn-ink">Stock is not yet available at the source location. Check the line availability below, then try Mark ready again.</p>}
    <div className="grid gap-7 xl:grid-cols-[minmax(0,1.6fr)_minmax(270px,.85fr)]">
      <div className="space-y-7">
        <section className="rounded-lg border border-border"><div className="border-b border-border px-5 py-4"><h2 className="text-base font-semibold">Document details</h2></div><dl className="grid gap-5 p-5 sm:grid-cols-2"><div><dt className="text-xs text-ink-muted">{type === "receipt" ? "Supplier" : type === "delivery" ? "Customer" : "Contact"}</dt><dd className="mt-1 text-sm font-medium">{operation.contact}</dd></div><div><dt className="text-xs text-ink-muted">Scheduled</dt><dd className="mt-1 text-sm font-medium">{formatDate(operation.scheduledAt)}</dd></div>{type !== "receipt" && <div><dt className="text-xs text-ink-muted">{type === "adjustment" ? "Count location" : "From"}</dt><dd className="mt-1 text-sm font-medium">{source}</dd></div>}{(type === "receipt" || type === "transfer") && <div><dt className="text-xs text-ink-muted">To</dt><dd className="mt-1 text-sm font-medium">{destination}</dd></div>}<div><dt className="text-xs text-ink-muted">Responsible</dt><dd className="mt-1 text-sm font-medium">{operation.responsible}</dd></div>{type === "adjustment" && <div><dt className="text-xs text-ink-muted">Reason</dt><dd className="mt-1 text-sm font-medium">{operation.reason}</dd></div>}</dl></section>
        <section className="min-w-0"><h2 className="mb-3 text-base font-semibold">{type === "adjustment" ? "Counted stock" : "Products"}</h2><div className="space-y-2 sm:hidden">{operation.lines.map((line) => { const product = state.products.find((item) => item.id === line.productId); return <div key={line.productId} className="rounded-lg border border-border p-4"><span className="block text-sm font-medium">{productName(state, line.productId)}</span><span className="block font-mono text-[11px] text-ink-muted">{product?.sku}</span><dl className="mt-3 flex flex-wrap gap-x-6 gap-y-2 border-t border-border-subtle pt-3"><div><dt className="text-[11px] text-ink-muted">{type === "adjustment" ? "Counted" : "Quantity"}</dt><dd className="mt-1 font-mono text-sm">{formatQuantity(line.quantity)} {product?.unit}</dd></div>{type !== "receipt" && <div><dt className="text-[11px] text-ink-muted">Source availability</dt><dd className="mt-1 font-mono text-sm">{operation.sourceLocationId ? formatQuantity(type === "adjustment" ? onHand(state,line.productId,operation.sourceLocationId) : available(state,line.productId,operation.sourceLocationId) + (operation.status === "Ready" ? line.quantity : 0)) : "—"} {product?.unit}</dd></div>}</dl></div>; })}</div><div className="hidden overflow-x-auto rounded-lg border border-border sm:block"><table className={tableClass}><thead><tr><th className={thClass}>Product</th><th className={thClass}>{type === "adjustment" ? "Counted" : "Quantity"}</th><th className={thClass}>Unit</th>{type !== "receipt" && <th className={thClass}>Source availability</th>}</tr></thead><tbody>{operation.lines.map((line) => {const product=state.products.find((item)=>item.id===line.productId);return <tr key={line.productId}><td className={tdClass}><span className="font-medium">{productName(state,line.productId)}</span><span className="block font-mono text-[11px] text-ink-muted">{product?.sku}</span></td><td className={`${tdClass} font-mono`}>{formatQuantity(line.quantity)}</td><td className={tdClass}>{product?.unit}</td>{type !== "receipt" && <td className={`${tdClass} font-mono text-xs`}>{operation.sourceLocationId ? formatQuantity(type === "adjustment" ? onHand(state,line.productId,operation.sourceLocationId) : available(state,line.productId,operation.sourceLocationId) + (operation.status === "Ready" ? line.quantity : 0)) : "—"} {product?.unit}</td>}</tr>;})}</tbody></table></div>{type === "adjustment" && <p className="mt-3 text-xs text-ink-muted">Recorded when opened: {formatQuantity(operation.countBaseline ?? 0)}. A count is rejected if stock changed afterward.</p>}</section>
      </div>
      <aside className="space-y-5"><section className="rounded-lg border border-border p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-muted">Progress</p><div className="mt-5 space-y-4">{statusFlow.map((status,index) => <div className="flex items-center gap-3" key={status}><span className={`flex h-6 w-6 items-center justify-center rounded-full text-[11px] font-semibold ${operation.status === status ? "bg-brand-strong text-white" : "bg-secondary text-ink-muted"}`}>{index+1}</span><span className={`text-sm ${operation.status === status ? "font-semibold text-foreground" : "text-ink-muted"}`}>{status}</span></div>)}</div></section><section className="rounded-lg border border-border bg-secondary p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-muted">What changes stock?</p><p className="mt-2 text-sm leading-6 text-ink">{type === "receipt" ? "Receiving the goods adds each line to the destination balance." : type === "delivery" ? "Completing dispatch subtracts each line from the source balance." : type === "transfer" ? "Completion subtracts from source and adds the same quantity to destination." : "Posting the count records the difference between recorded and counted stock."}</p></section></aside>
    </div>
  </>;
}
