"use client";

import { useState } from "react";
import Link from "next/link";
import { useDemo } from "../../context/demo-context";
import { formatDate, formatQuantity, locationName, onHand, reserved, totalOnHand } from "../../lib/inventory";
import { Drawer, EmptyState, PageHeading, StatusBadge, primaryButton, secondaryButton, tableClass, tdClass, thClass } from "../ui/primitives";
import { ProductForm } from "./product-form";

export function ProductDetailView({ id }: { id: string }) {
  const [editOpen, setEditOpen] = useState(false);
  const { state } = useDemo();
  const product = state.products.find((item) => item.id === id);
  if (!product) return <EmptyState title="Product not found" description="This product is not in the catalog." action={<Link href="/products" className={secondaryButton}>Back to products</Link>} />;
  const total = totalOnHand(state,product.id);
  const movements = [...state.movements].filter((item) => item.productId === id).reverse().slice(0, 5);
  return <>
    <PageHeading eyebrow="Product detail" title={product.name} description={`${product.sku} · ${product.category}`} action={<div className="flex flex-wrap gap-2"><Link href="/products" className={secondaryButton}>Back to products</Link><Link href={`/operations/adjustments?new=1&product=${product.id}`} className={secondaryButton}>Update stock</Link><button className={primaryButton} type="button" onClick={() => setEditOpen(true)}>Edit product</button></div>} />
    <div className="mb-7 grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-border p-5"><p className="text-xs text-ink-muted">On hand</p><p className="mt-2 font-mono text-3xl font-medium">{formatQuantity(total)} <span className="text-base text-ink-muted">{product.unit}</span></p></div><div className="rounded-lg border border-border p-5"><p className="text-xs text-ink-muted">Reorder point</p><p className="mt-2 font-mono text-3xl font-medium">{product.reorderPoint} <span className="text-base text-ink-muted">{product.unit}</span></p></div><div className="rounded-lg border border-border p-5"><p className="text-xs text-ink-muted">Availability</p><div className="mt-3">{total === 0 ? <StatusBadge status="Out" /> : total <= product.reorderPoint ? <StatusBadge status="Low" /> : <span className="text-sm font-medium text-ok-ink">In stock</span>}</div></div></div>
    <div className="grid min-w-0 gap-7 xl:grid-cols-[1.4fr_1fr]"><section className="min-w-0"><h2 className="mb-3 text-base font-semibold">Stock by location</h2><div className="space-y-2 sm:hidden">{state.locations.map((location) => <div key={location.id} className="rounded-lg border border-border p-4"><h3 className="text-sm font-medium">{locationName(state, location.id)}</h3><dl className="mt-3 grid grid-cols-3 gap-2 border-t border-border-subtle pt-3"><div><dt className="text-[10px] text-ink-muted">On hand</dt><dd className="mt-1 font-mono text-xs">{formatQuantity(onHand(state,id,location.id))}</dd></div><div><dt className="text-[10px] text-ink-muted">Reserved</dt><dd className="mt-1 font-mono text-xs">{formatQuantity(reserved(state,id,location.id))}</dd></div><div><dt className="text-[10px] text-ink-muted">Free</dt><dd className="mt-1 font-mono text-xs">{formatQuantity(onHand(state,id,location.id)-reserved(state,id,location.id))}</dd></div></dl></div>)}</div><div className="hidden overflow-x-auto rounded-lg border border-border sm:block"><table className={tableClass}><thead><tr><th className={thClass}>Location</th><th className={`${thClass} text-right`}>On hand</th><th className={`${thClass} text-right`}>Reserved</th><th className={`${thClass} text-right`}>Free to use</th></tr></thead><tbody>{state.locations.map((location) => <tr key={location.id}><td className={tdClass}>{locationName(state,location.id)}</td><td className={`${tdClass} text-right font-mono`}>{formatQuantity(onHand(state,id,location.id))}</td><td className={`${tdClass} text-right font-mono`}>{formatQuantity(reserved(state,id,location.id))}</td><td className={`${tdClass} text-right font-mono`}>{formatQuantity(onHand(state,id,location.id)-reserved(state,id,location.id))}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-ink-muted">To correct stock, create a physical count under Adjustments.</p></section><section className="min-w-0"><h2 className="mb-3 text-base font-semibold">Latest movements</h2><div className="overflow-hidden rounded-lg border border-border">{movements.map((movement) => <div key={movement.id} className="flex items-start justify-between gap-3 border-b border-border-subtle px-4 py-3 last:border-0"><span className="min-w-0"><span className="block truncate font-mono text-xs">{state.operations.find((item) => item.id === movement.operationId)?.reference ?? movement.reference}</span><span className="text-xs text-ink-muted">{locationName(state,movement.locationId)} · {formatDate(movement.at)}</span></span><span className={`shrink-0 font-mono text-xs font-medium ${movement.quantity >= 0 ? "text-ok-ink" : "text-bad-ink"}`}>{movement.quantity > 0 ? "+" : ""}{movement.quantity} {product.unit}</span></div>)}</div></section></div>
    {editOpen && <Drawer title="Edit product" onClose={() => setEditOpen(false)}><ProductForm product={product} onClose={() => setEditOpen(false)} /></Drawer>}
  </>;
}
